services:
  - type: web
    name: ontdek-polen
    env: node
    buildCommand: npm run build
    startCommand: node dist/index.js
    envVars:
      - key: NODE_ENV
        value: production
      - key: DATABASE_URL
        fromDatabase:
          name: ontdek-polen-db
          property: connectionString
    autoDeploy: true
    rootDir: .
    disk:
      name: ontdek-polen-disk
      mountPath: /var/data
      sizeGB: 1

databases:
  - name: ontdek-polen-db
    databaseName: ontdek_polen
    user: postgres